package info.doula.domain;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import org.springframework.web.util.HtmlUtils;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by saad on 9/28/2016.
 */
@Entity
@Table(name = "users")
public class Users {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    @NotNull
    @Email
    @Length(min = 3, max = 100)
    @Column(unique = true)
    private String email;

    @NotNull
    @Length(min = 1, max = 50)
    private String firstName;

    @NotNull
    @Length(min = 1, max = 50)
    private String lastName;

    @Transient
    private String vaultId;

    @Transient
    private ArrayList<String> vaultIds;

    @Transient
    private String sponsorCode;

    @Transient
    private List<Integer> sponsoredAdvisorUserId;

    @Transient
    private Sponsor sponsor;

    @Transient
    private int packageId;

    @Transient
    private String packageName;

    @Transient
    private double packagePrice;

    @Transient
    private Integer inviteOnly;

    @Transient
    private SponsoredAdvisor sponsoredAdvisor;

    @Transient
    private boolean trustedAdvisor;

    @Transient
    private String sponsorName;

    @Transient
    private String sponsorCompanyName;

    @Transient
    private boolean exceedLimit;

    private boolean active;

    @Length(min = 1, max = 100)
    private String invitationCode;

    private boolean acceptedLicence;

    public Users() {
    }

    public Users(int id) {
        this.id = id;
    }

    public Users(String email, String firstName, String lastName) {
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    // Getter and setter methods

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = HtmlUtils.htmlEscape(firstName);
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = HtmlUtils.htmlEscape(lastName);
    }

    public String getVaultId() {
        return vaultId;
    }

    public void setVaultId(String vaultId) {
        this.vaultId = vaultId;
    }

    public String getSponsorCode() {
        return sponsorCode;
    }

    public void setSponsorCode(String sponsorCode) {
        this.sponsorCode = sponsorCode;
    }

    public Sponsor getSponsor() {
        return sponsor;
    }

    public void setSponsor(Sponsor sponsor) {
        this.sponsor = sponsor;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public ArrayList<String> getVaultIds() {
        return vaultIds;
    }

    public void setVaultIds(ArrayList<String> vaultIds) {
        this.vaultIds = vaultIds;
    }

    public List<Integer> getSponsoredAdvisorUserId() {
        return sponsoredAdvisorUserId;
    }

    public void setSponsoredAdvisorUserId(List<Integer> sponsoredAdvisorUserId) {
        this.sponsoredAdvisorUserId = sponsoredAdvisorUserId;
    }

    public String getInvitationCode() {
        return invitationCode;
    }

    public void setInvitationCode(String invitationCode) {
        this.invitationCode = invitationCode;
    }

    public boolean isAcceptedLicence() {
        return acceptedLicence;
    }

    public void setAcceptedLicence(boolean acceptedLicence) {
        this.acceptedLicence = acceptedLicence;
    }

    public int getPackageId() {
        return packageId;
    }

    public void setPackageId(int packageId) {
        this.packageId = packageId;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public double getPackagePrice() {
        return packagePrice;
    }

    public void setPackagePrice(double packagePrice) {
        this.packagePrice = packagePrice;
    }

    public Integer getInviteOnly() {
        return inviteOnly;
    }

    public void setInviteOnly(Integer inviteOnly) {
        this.inviteOnly = inviteOnly;
    }

    public SponsoredAdvisor getSponsoredAdvisor() {
        return sponsoredAdvisor;
    }

    public void setSponsoredAdvisor(SponsoredAdvisor sponsoredAdvisor) {
        this.sponsoredAdvisor = sponsoredAdvisor;
    }

    public boolean isTrustedAdvisor() {
        return trustedAdvisor;
    }

    public void setTrustedAdvisor(boolean trustedAdvisor) {
        this.trustedAdvisor = trustedAdvisor;
    }

    public String getSponsorName() {
        return sponsorName;
    }

    public void setSponsorName(String sponsorName) {
        this.sponsorName = sponsorName;
    }

    public String getSponsorCompanyName() {
        return sponsorCompanyName;
    }

    public void setSponsorCompanyName(String sponsorCompanyName) {
        this.sponsorCompanyName = sponsorCompanyName;
    }

    public boolean isExceedLimit() {
        return exceedLimit;
    }

    public void setExceedLimit(boolean exceedLimit) {
        this.exceedLimit = exceedLimit;
    }
}
